// Generated by tools/pwa.mjs — do not edit by hand.
//
// Cache-first for everything precached: the games are static and the whole
// point is that they keep working with no network. A new build changes CACHE,
// which drops the old one wholesale rather than trying to reconcile it.
//
// The list is stored relative to this file and resolved against it, not
// against the server root: on GitHub Pages the site is published under
// /<repo>/, and a leading slash would send every request to the wrong origin
// path. sw.js sits at the site root, so its own URL is the correct base.
const CACHE = 'vmsw92b08';
const HERE = (p) => new URL(p, self.location).toString();
const ASSETS = [
 "web/game.html",
 "web/manifest.webmanifest",
 "src/anim/gait.js",
 "src/anim/idle.js",
 "src/anim/lipsync.js",
 "src/anim/stage.js",
 "src/anim/timeline.js",
 "src/base.js",
 "src/book/effects.js",
 "src/book/pages.js",
 "src/characters.js",
 "src/copy.js",
 "src/enhance.js",
 "src/expressions.js",
 "src/game/build.js",
 "src/game/chimney.js",
 "src/game/door.js",
 "src/game/faces.js",
 "src/game/house.js",
 "src/game/menu.js",
 "src/game/rebuild.js",
 "src/game/run.js",
 "src/game/ui.js",
 "src/game/voices.js",
 "src/game/whosaid.js",
 "src/rig.js",
 "src/targets/book.js",
 "src/targets/inspect-poster.js",
 "src/targets/inspect-scenes.js",
 "src/targets/inspect.js",
 "src/targets/poster.js",
 "src/targets/promo-narrated-plain.js",
 "src/targets/promo-narrated.js",
 "src/targets/promo.js",
 "src/targets/test-fragments.js",
 "src/targets/test-open.js",
 "assets/fonts/BalooBhaijaan2-400.woff2",
 "assets/fonts/BalooBhaijaan2-600.woff2",
 "assets/fonts/BalooBhaijaan2-800.woff2",
 "assets/fonts/Cairo-400.woff2",
 "assets/fonts/Cairo-600.woff2",
 "assets/fonts/Cairo-700.woff2",
 "assets/fonts/embed.css",
 "assets/audio/sfx/breath.wav",
 "assets/audio/sfx/chirp.wav",
 "assets/audio/sfx/forest.wav",
 "assets/audio/sfx/growl.wav",
 "assets/audio/sfx/impact.wav",
 "assets/audio/sfx/knock.wav",
 "assets/audio/sfx/step-grass.wav",
 "assets/audio/sfx/step-wolf.wav",
 "assets/audio/sfx/whoosh.wav",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D9%85%D8%B4%D9%87%D8%AF8.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D9%85%D8%B4%D9%87%D8%AF17%D9%8818.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D9%85%D8%B4%D9%87%D8%AF12.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D9%85%D8%B4%D9%87%D8%AF14.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D9%85%D8%B4%D9%87%D8%AF25%D8%AC%D8%B2%D8%A12.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA%20svg/%D8%AE%D9%84%D9%81%D9%8A%D9%87%201.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%B4%D8%AE%D8%B5%D9%8A%D8%A7%D8%AA%20svg/%D8%B0%D9%8A%D8%A8.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%B4%D8%AE%D8%B5%D9%8A%D8%A7%D8%AA%20svg/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%83%D8%A8%D8%B1.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%B4%D8%AE%D8%B5%D9%8A%D8%A7%D8%AA%20svg/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%88%D8%B3%D8%B7.svg",
 "assets/incoming/%D8%AE%D9%84%D9%81%D9%8A%D8%A7%D8%AA/%D8%B4%D8%AE%D8%B5%D9%8A%D8%A7%D8%AA%20svg/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D8%B5%D8%BA%D8%B1.svg",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%B9%D8%A7%D8%B4%D8%B1/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%B9%D8%A7%D8%B4%D8%B1/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8%202.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%AE%D8%A7%D9%85%D8%B3%20%D8%B9%D8%B4%D8%B1/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%AA%D8%A7%D8%B3%D8%B9%20%D8%B9%D8%B4%D8%B1/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%AD%D8%A7%D8%AF%D9%8A%20%D9%88%D8%A7%D9%84%D8%B9%D8%B4%D8%B1%D9%88%D9%86/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%AB%D8%A7%D9%86%D9%8A%20%D9%88%D8%A7%D9%84%D8%B9%D8%B4%D8%B1%D9%88%D9%86/%D8%A7%D9%84%D8%B0%D8%A6%D8%A8.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%AB%D8%A7%D9%84%D8%AB%20%D8%B9%D8%B4%D8%B1/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D8%B5%D8%BA%D8%B1-1.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%B9%D8%B4%D8%B1%D9%88%D9%86/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D8%B5%D8%BA%D8%B1.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%88%D8%B3%D8%B7%201.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D9%85%D8%B4%D9%87%D8%AF%20%D8%A7%D9%84%D8%AE%D8%A7%D9%85%D8%B3%20%D8%B9%D8%B4%D8%B1/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%88%D8%B3%D8%B7-1.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%AB%D8%A7%D9%86%D9%8A%20%D9%88%D8%A7%D9%84%D8%B9%D8%B4%D8%B1%D9%88%D9%86/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%83%D8%A8%D8%B1.mp3",
 "assets/audio/%D8%B5%D9%88%D8%AA%D9%8A%D8%A7%D8%AA/%D8%A7%D9%84%D8%AB%D8%A7%D9%85%D9%86%20%D8%B9%D8%B4%D8%B1/%D8%A7%D9%84%D8%AE%D8%B1%D9%88%D9%81%20%D8%A7%D9%84%D8%A7%D9%83%D8%A8%D8%B1.mp3",
 "web/icons/icon-192.png",
 "web/icons/icon-512.png",
 "web/icons/maskable-512.png"
].map(HERE);

self.addEventListener('install', (e) => {
  // addAll fails the whole install if any single file 404s, which is the
  // behaviour we want: a half-cached game that breaks offline is worse than
  // one that never claimed to be installed.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request).catch(() =>
      // Offline and not cached: for a navigation, fall back to the menu.
      e.request.mode === 'navigate' ? caches.match(HERE('web/game.html')) : Response.error()))
  );
});
