// Fetch Arabic faces from Google Fonts and emit a self-contained @font-face
// stylesheet with base64 data URIs, so exported SVGs render identically
// anywhere without external font files.
//
//   node tools/fonts.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'fonts');
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

// family spec -> weights we actually use
const WANT = [
  { family: 'Baloo Bhaijaan 2', spec: 'Baloo+Bhaijaan+2:wght@400;600;800', alias: 'Poster Display' },
  { family: 'Cairo', spec: 'Cairo:wght@400;600;700', alias: 'Poster Text' },
];

fs.mkdirSync(OUT, { recursive: true });

/** Split a Google Fonts CSS payload into @font-face blocks. */
function faces(css) {
  return [...css.matchAll(/@font-face\s*\{([^}]*)\}/g)].map((m) => {
    const body = m[1];
    const get = (k) => (body.match(new RegExp(k + '\\s*:\\s*([^;]+);')) || [])[1]?.trim();
    return {
      family: (get('font-family') || '').replace(/['"]/g, ''),
      weight: get('font-weight') || '400',
      style: get('font-style') || 'normal',
      range: get('unicode-range') || '',
      url: (body.match(/url\((https:[^)]+)\)/) || [])[1],
    };
  });
}

const isArabic = (r) => /U\+06|U\+0600|U\+FE|U\+FB5/i.test(r);

let out = '/* Generated by tools/fonts.mjs — embedded Arabic faces (SIL OFL). */\n';
const report = [];

for (const w of WANT) {
  const url = `https://fonts.googleapis.com/css2?family=${w.spec}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  const arabic = faces(css).filter((f) => isArabic(f.range) && f.url);

  if (!arabic.length) {
    report.push(`${w.family}: no Arabic face found`);
    continue;
  }

  // One face per weight, preferring the widest Arabic range.
  const byWeight = new Map();
  for (const f of arabic) if (!byWeight.has(f.weight)) byWeight.set(f.weight, f);

  for (const [weight, f] of byWeight) {
    const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    const b64 = buf.toString('base64');
    out +=
      `@font-face{font-family:'${w.alias}';font-style:normal;font-weight:${weight};` +
      `font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
    report.push(`${w.alias} ${weight}  ${(buf.length / 1024).toFixed(0)} KB`);
    // Keep a raw copy so the fonts can be installed for Illustrator/Inkscape.
    fs.writeFileSync(path.join(OUT, `${w.family.replace(/\s+/g, '')}-${weight}.woff2`), buf);
  }
}

fs.writeFileSync(path.join(OUT, 'embed.css'), out, 'utf8');
console.log(report.join('\n'));
console.log(`\nembed.css  ${(out.length / 1024).toFixed(0)} KB  ->  assets/fonts/embed.css`);
