// Cut the house artwork into the pieces the building games need.
//
//   node tools/house-split.mjs            -> assets .../بيت-مجزأ.svg
//   node tools/house-split.mjs --proof    -> also an exploded view to check
//
// بيت.svg arrives as 794 loose paths with no groups at all — one id on the
// frame and S2..S794 on everything else. The games need three pieces that can
// be built, dragged and knocked down independently, so the grouping has to be
// recovered from geometry.
//
// The structure is legible once measured. The roof is two big halves spanning
// y 123..359; the door is a stack of four dark paths at x 399..524, y 385..598;
// the walls are everything else. Classifying by where a path's box sits gets
// all 794 into the right pile — see --proof, which paints each pile and pulls
// them apart so a wrong one is obvious.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';

const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'assets/incoming/خلفيات/شخصيات svg/بيت.svg');
const OUT = path.join(ROOT, 'assets/incoming/خلفيات/شخصيات svg/بيت-مجزأ.svg');

// Measured off the artwork.
const ROOF_BOTTOM = 360;                       // lowest the roof reaches
const DOOR = { x0: 392, x1: 532, y0: 378, y1: 600 };

const proof = process.argv.includes('--proof');

const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new' });
try {
  const src = fs.readFileSync(SRC, 'utf8');
  const page = await browser.newPage();
  await page.setContent(`<body style="margin:0">${src}</body>`, { waitUntil: 'networkidle0' });

  const parts = await page.evaluate((ROOF_BOTTOM, DOOR) => {
    const svg = document.querySelector('svg');
    const out = { roof: [], walls: [], door: [] };
    const boxes = {};
    for (const p of svg.querySelectorAll('path')) {
      const b = p.getBBox();
      const cx = b.x + b.width / 2, cy = b.y + b.height / 2;
      // The door first: it sits inside the wall's area, so a y-only rule would
      // swallow it.
      const inDoor = cx > DOOR.x0 && cx < DOOR.x1 && cy > DOOR.y0 && cy < DOOR.y1
        && b.x > DOOR.x0 - 30 && b.x + b.width < DOOR.x1 + 30;
      const key = inDoor ? 'door' : (cy < ROOF_BOTTOM ? 'roof' : 'walls');
      out[key].push(p.getAttribute('id'));
      const acc = (boxes[key] ||= { x0: 1e9, y0: 1e9, x1: -1e9, y1: -1e9 });
      acc.x0 = Math.min(acc.x0, b.x); acc.y0 = Math.min(acc.y0, b.y);
      acc.x1 = Math.max(acc.x1, b.x + b.width); acc.y1 = Math.max(acc.y1, b.y + b.height);
    }
    const box = svg.getBBox();
    // Each group's own box, measured here and written into the file. house.js
    // needs it to place the parts, and getBBox() only works on a node that is
    // in the document — measuring at build time saves every consumer from
    // mounting the artwork just to find out how big a roof is.
    const part = {};
    for (const [k, a] of Object.entries(boxes)) {
      part[k] = { x: +a.x0.toFixed(1), y: +a.y0.toFixed(1),
                  w: +(a.x1 - a.x0).toFixed(1), h: +(a.y1 - a.y0).toFixed(1) };
    }
    return { out, part, box: { x: +box.x.toFixed(1), y: +box.y.toFixed(1),
                               w: +box.width.toFixed(1), h: +box.height.toFixed(1) } };
  }, ROOF_BOTTOM, DOOR);

  const { out, part, box } = parts;
  console.log(`house  ${box.w.toFixed(0)} x ${box.h.toFixed(0)} at ${box.x},${box.y}`);
  console.log(`       roof ${out.roof.length}  walls ${out.walls.length}  door ${out.door.length}` +
              `  (total ${out.roof.length + out.walls.length + out.door.length})`);
  for (const k of ['roof', 'walls', 'door']) {
    const b = part[k];
    console.log(`       ${k.padEnd(5)} box  x=${b.x} y=${b.y} w=${b.w} h=${b.h}`);
  }

  // Rebuild the file with three groups, keeping every path's original order so
  // the overlaps still paint correctly.
  const ids = new Map();
  for (const [k, list] of Object.entries(out)) for (const id of list) ids.set(id, k);
  const NAME = { roof: 'السقف', walls: 'الجدران', door: 'الباب' };

  const bodies = { roof: [], walls: [], door: [] };
  for (const m of src.matchAll(/<path\b[^>]*\/>/g)) {
    const id = (m[0].match(/id="([^"]+)"/) || [])[1];
    const k = ids.get(id);
    if (k) bodies[k].push(m[0]);
  }

  const doc = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/house-split.mjs from بيت.svg — do not edit by hand.
     Three groups recovered from geometry; the source has none. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${box.w}" height="${box.h}"
     viewBox="${box.x} ${box.y} ${box.w} ${box.h}">
${['walls', 'roof', 'door'].map((k) =>
  `<g id="${NAME[k]}" data-part="${k}" data-box="${part[k].x} ${part[k].y} ${part[k].w} ${part[k].h}">\n${bodies[k].join('\n')}\n</g>`).join('\n')}
</svg>
`;
  fs.writeFileSync(OUT, doc);
  console.log(`       wrote ${path.relative(ROOT, OUT)}  ${(doc.length / 1024).toFixed(0)} KB`);

  if (proof) {
    // Pull the pieces apart and tint each, so a misfiled path shows up.
    const tint = { walls: '#00a2ff', roof: '#ff3b00', door: '#00ff66' };
    const shift = { walls: [0, 0], roof: [0, -120], door: [-190, 90] };
    const exploded = `<svg xmlns="http://www.w3.org/2000/svg"
        viewBox="${box.x - 220} ${box.y - 140} ${box.w + 440} ${box.h + 280}" width="1180">
      <rect x="${box.x - 220}" y="${box.y - 140}" width="${box.w + 440}" height="${box.h + 280}" fill="#f6f2e8"/>
      ${['walls', 'roof', 'door'].map((k) => `
        <g transform="translate(${shift[k][0]} ${shift[k][1]})">
          <g>${bodies[k].join('')}</g>
          <g opacity="0.34">${bodies[k].join('').replace(/fill="#[0-9a-fA-F]+"/g, `fill="${tint[k]}"`)}</g>
        </g>`).join('')}
    </svg>`;
    const p2 = await browser.newPage();
    await p2.setViewport({ width: 1180, height: Math.round(1180 * (box.h + 280) / (box.w + 440)) });
    await p2.setContent(`<body style="margin:0">${exploded}</body>`, { waitUntil: 'networkidle0' });
    const shot = path.join(ROOT, 'out/house-split.png');
    fs.mkdirSync(path.dirname(shot), { recursive: true });
    await p2.screenshot({ path: shot });
    console.log(`       proof  out/house-split.png  (roof red, walls blue, door green)`);
  }
} finally {
  await browser.close();
}
